#!/bin/bash
# deploy/db/04-app-user.sh
# Runs ONCE, when the database volume is created for the first time
# (the cloud version of database/create_app_user.sql).
# The password comes from the environment (deploy/.env, generated by start.sh), never from git.
# Host '%' instead of 'localhost': the PHP container connects over the Docker network.
# docker_process_sql is a helper from the official MariaDB image's startup script.
docker_process_sql <<-EOSQL
	CREATE USER 'maintenance_app'@'%' IDENTIFIED BY '${APP_DB_PASSWORD}';
	GRANT SELECT, INSERT, UPDATE, DELETE ON maintenance_dashboard.* TO 'maintenance_app'@'%';
EOSQL
